Numpy Practice

In [1]:
import numpy as np

In [8]:
a = np.array([1,2,3,5,7], dtype="i")

In [10]:
b = np.array([2,3,5], dtype="f")

In [11]:
print(a)

[1 2 3 5 7]


In [12]:
print(b)

[2. 3. 5.]


In [13]:
type(a)

numpy.ndarray

In [14]:
a.dtype

dtype('int32')

In [15]:
b.dtype

dtype('float32')

In [17]:
a= np.array([[1,2,3],[4,5,6]])

In [18]:
print(a)

[[1 2 3]
 [4 5 6]]


In [20]:
a.ndim   #Checks Dimension

2

In [21]:
a[0,2]

3

In [22]:
b= np.array([[1,2,3],[4,5,6,7]])

C:\Users\aksha\AppData\Local\Temp\ipykernel_16748\2363990108.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b= np.array([[1,2,3],[4,5,6,7]])


In [23]:
b.ndim

1

In [24]:
print(b)

[list([1, 2, 3]) list([4, 5, 6, 7])]


In [25]:
a.shape

(2, 3)

In [26]:
a.size

6

In [27]:
a.nbytes

24

In [28]:
A= np.arange(100)

In [29]:
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [30]:
A= np.arange(20,100)
print(A)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91
 92 93 94 95 96 97 98 99]


In [32]:
A = np.random.permutation(np.arange(10))
print(A)

[7 9 4 5 3 6 0 8 2 1]


In [33]:
A= np.random.rand(10)

In [34]:
A

array([0.40268084, 0.68808811, 0.1074391 , 0.06217631, 0.49036377,
       0.74867889, 0.84577288, 0.04469146, 0.6733459 , 0.25881762])