In [1]:
import pandas as pd

In [3]:
print(pd.__version__)

2.0.2


In [4]:
A = pd.Series([2,3,4,5], index=['a','b','c','d'])

In [5]:
A.values

array([2, 3, 4, 5], dtype=int64)

In [6]:
type(A.values)

numpy.ndarray

In [7]:
type(A)

pandas.core.series.Series

In [8]:
A.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [9]:
A['a']

2

In [10]:
A['a':'c']

a    2
b    3
c    4
dtype: int64

In [11]:
grads_dict={'A':4, 'B':5, 'C':6}
grads= pd.Series(grads_dict)

In [12]:
grads.values

array([4, 5, 6], dtype=int64)

In [13]:
grads

A    4
B    5
C    6
dtype: int64

In [14]:
grads['B']

5

In [15]:
grads[0:2]

A    4
B    5
dtype: int64

In [16]:
marks_dict={'A':85, 'B':96, 'C':75}
marks= pd.Series(marks_dict)

In [17]:
marks

A    85
B    96
C    75
dtype: int64

In [18]:
D = pd.DataFrame({'Grades':grads,'Marks':marks})

In [19]:
D

Grades  Marks
A       4     85
B       5     96
C       6     75

In [20]:
D.T

A   B   C
Grades   4   5   6
Marks   85  96  75

In [21]:
D.values

array([[ 4, 85],
       [ 5, 96],
       [ 6, 75]], dtype=int64)

In [22]:
D.values[2,0]

6

In [23]:
D.columns

Index(['Grades', 'Marks'], dtype='object')

In [25]:
D['ScaledMarks']= 100*(D['Marks']/90)

In [26]:
D

Grades  Marks  ScaledMarks
A       4     85    94.444444
B       5     96   106.666667
C       6     75    83.333333

In [27]:
del D['ScaledMarks']

In [28]:
D

Grades  Marks
A       4     85
B       5     96
C       6     75

In [31]:
G= D[D['Marks']>80]

In [32]:
G

Grades  Marks
A       4     85
B       5     96

In [35]:
A= pd.DataFrame([{'a':1,'b':2},{'b':4, 'c':5}])

In [36]:
A

a  b    c
0  1.0  2  NaN
1  NaN  4  5.0

In [37]:
A.fillna(0)

a  b    c
0  1.0  2  0.0
1  0.0  4  5.0

In [38]:
A= pd.Series(['a','b','c'],index=[1,3,5])

In [39]:
A[1]

'a'

In [40]:
A[1:3]

3    b
5    c
dtype: object

In [41]:
A.loc[1:3]

1    a
3    b
dtype: object

In [42]:
A.iloc[1:3]

3    b
5    c
dtype: object

In [43]:
D

Grades  Marks
A       4     85
B       5     96
C       6     75

In [44]:
D.iloc[2,:]

Grades     6
Marks     75
Name: C, dtype: int64

In [45]:
from sklearn.impute import SimpleImputer

In [ ]:
df= pd.read_csv('file_location/file_name.csv')

In [ ]:
df.head()     #Displays entire table

In [ ]:
df.drop(['Column_name'],inplace=True)  #Delete entire column

In [ ]:
df.describe()

In [ ]:
df.info()

In [ ]:
df2= df.groupby('Country')[['Column_1','Column_2']]